### ISSUE TITLE
Change texture on loaded meshs

### ISSUE THREAD

**Issue by eXponenta** [jeske/SimpleScene#17]
How change texture on OBJ or md5 meshs? 
Changing **Mesh.textureMaterial** or **Object.textureMaterial** does not work.
After loading and instancing mesh on scene **.texture Material **always NULL.

**Comment by HoneyHazard** [comment]
Currently we have things like this: mesh texture material, when not null, overrides object texture material. Geometry subset texture material, when not null, overrides mesh texture material. However, geometry subsets were not publically accessible leaving you with no way to change the textures. I've made this variable public just now and did a similar thing for skeletal submeshes. See this commit https://github.com/jeske/SimpleScene/commit/37234bba464f877fb4698807be86b059f636cdc8

You can now assign submesh textures like this:


var asWf = droneObj1.Mesh as SSMesh_wfOBJ;
var tex = SSAssetManager.GetInstance<SSTexture> ("checkerboard.png");
var texMat = new SSTextureMaterial (diffuse: tex);
foreach (var subset in asWf.geometrySubsets) {
        subset.TextureMaterial = texMat;
}

I can see how this is non-ideal because it overrides texture on ALL instances of the mesh. We will have to think on how to implement in otherwise, but I hope it will not be stopping you from doing what you are doing in the meantime.

![screenshot_2016-04-11_09-24-31](https://cloud.githubusercontent.com/assets/8847050/14434368/3d38559a-ffc7-11e5-8275-e3a75f4f493f.png)

**Comment by jeske** [comment]
Keep in mind, that even if you set a different texture, the UV coordinates
are still being drawn from the OBJ file. This means the UV layout of your
texture needs to match the UV layout exported with the OBJ file.

If you wish to use a different UV layout, you'll need to load the OBJ into
a program like blender, change the UV layout, and re-export.

At some point it might make sense to include simple programmatic UV layouts
just for basic code experimentation, such as cylindrical, spherical,
cubemap, etc. These are not usually useful in practice, so they havn't been
added yet.

**Comment by eXponenta** [comment]
Thanks!
